name: Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle wrapper
        run: |
          echo "Validating Gradle wrapper..."
          ./gradlew --version

      - name: Download dependencies
        run: |
          echo "Downloading project dependencies..."
          ./gradlew dependencies --configuration runtimeClasspath

      - name: Compile project
        run: |
          echo "Compiling Java sources..."
          echo "Java version: $(java -version 2>&1 | head -1)"
          echo "Gradle version: $(./gradlew --version | grep 'Gradle' | head -1)"
          ./gradlew build

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image to GitHub Packages
        if: github.event_name != 'pull_request'
        run: |
          echo "Publishing Docker image to GitHub Packages..."
          ./gradlew jib -Djib.console=plain \
            -Pcontainer.image.registry="ghcr.io/${{ github.repository_owner }}" \
            -Pcontainer.image.name="${{ github.event.repository.name }}"
